spring:
    datasource:
        url:    jdbc:postgresql://localhost:5432/jwtDB
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: 31081995
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect